// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChbbUznYE87a1AH7c4One44NfV_p9TxoU',
    appId: '1:274683053972:web:4e7e1adc3e240b876ff181',
    messagingSenderId: '274683053972',
    projectId: 'geminiproject-8998b',
    authDomain: 'geminiproject-8998b.firebaseapp.com',
    storageBucket: 'geminiproject-8998b.appspot.com',
    measurementId: 'G-9XTQ6PT993',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1ZG1213woOEpp7dluTupUt6TbffUtDI0',
    appId: '1:274683053972:android:fe555be5cff5d14a6ff181',
    messagingSenderId: '274683053972',
    projectId: 'geminiproject-8998b',
    storageBucket: 'geminiproject-8998b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4u6LIwTlwfrOOnfrQ96_nL53zL5S-ueg',
    appId: '1:274683053972:ios:593d65f94d1a43be6ff181',
    messagingSenderId: '274683053972',
    projectId: 'geminiproject-8998b',
    storageBucket: 'geminiproject-8998b.appspot.com',
    iosBundleId: 'com.example.geminiproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4u6LIwTlwfrOOnfrQ96_nL53zL5S-ueg',
    appId: '1:274683053972:ios:593d65f94d1a43be6ff181',
    messagingSenderId: '274683053972',
    projectId: 'geminiproject-8998b',
    storageBucket: 'geminiproject-8998b.appspot.com',
    iosBundleId: 'com.example.geminiproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChbbUznYE87a1AH7c4One44NfV_p9TxoU',
    appId: '1:274683053972:web:835146b1cfe0ab2f6ff181',
    messagingSenderId: '274683053972',
    projectId: 'geminiproject-8998b',
    authDomain: 'geminiproject-8998b.firebaseapp.com',
    storageBucket: 'geminiproject-8998b.appspot.com',
    measurementId: 'G-TL6CLFJYJQ',
  );
}
