import 'package:flutter/material.dart';

const Map<String, List<String>> categorizedIcons = {
  'Finances': [
    'account_balance',
    'account_balance_wallet',
    'attach_money',
    'credit_card',
    'monetization_on',
    'money',
    'money_off',
    'payment',
    'receipt',
    'shopping_cart',
  ],
  'Transport': [
    'airplanemode_active',
    'airport_shuttle',
    'directions_bike',
  ],
  'Food and Drink': [
    'fastfood',
    'local_dining',
    'local_drink',
    'restaurant_menu'
  ],
  'Home': [
    'home',
    'house',
    'house_siding',
    'houseboat',
    'meeting_room',
    'roofing',
  ],
  'Health': [
    'health_and_safety',
    'local_hospital',
    'local_pharmacy',
    'medical_services',
    'sanitizer',
  ],
  'Beauty': [
    'face',
    'spa',
    'sports_bar',
    'sports_baseball',
    'sports_basketball'
  ],
  'Entertainment': [
    'movie',
    'music_note',
    'theaters',
    'videogame_asset',
  ],
  'Accounts': [
    'account_box',
    'account_circle',
    'account_tree',
    'add_ic_call',
    'admin_panel_settings',
    'alarm',
    'alarm_add',
    'alarm_off',
    'alarm_on',
    'all_inbox',
    'all_out',
    'analytics',
    'anchor',
    'android',
    'announcement',
    'api',
    'app_blocking',
    'arrow_circle_down',
    'arrow_circle_up',
    'arrow_right_alt',
  ],
  'Workout': [
    'sports_bar',
    'sports_baseball',
    'sports_basketball',
  ],
  'Relaxion': [
    'meditation',
    'self_improvement',
    'spa',
  ],
  'Education': [
    'book',
    'book_online',
    'class',
    'library_books',
    'school',
    'science',
  ],
  'Family/Children': [
    'child_friendly',
    'stroller',
    'toys',
  ],
  'Farm': [
    'agriculture',
    'grass',
    'landscape',
    'nature',
    'nature_people',
    'sailing',
    'terrain',
    'water',
  ],
  'other': [
    'add',
    'add_a_photo',
    'add_alarm',
    'add_alert',
    'add_box',
    'add_business',
    'add_call',
    'add_chart',
    'add_circle',
    'add_circle_outline',
    'add_comment',
    'add_ic_call',
    'add_location',
    'add_location_alt',
    'add_photo_alternate',
    'add_shopping_cart',
    'add_to_home_screen',
    'add_to_photos',
    'add_to_queue',
    'addchart',
    'adjust',
    'admin_panel_settings',
    'agriculture',
    'airline_seat_flat',
    'airline_seat_flat_angled',
    'airline_seat_individual_suite',
    'airline_seat_legroom_extra',
    'airline_seat_legroom_normal',
    'airline_seat_legroom_reduced',
    'airline_seat_recline_extra',
    'airline_seat_recline_normal',
    'airplanemode_active',
    'airplanemode_inactive',
    'airplay',
    'airport_shuttle',
    'alarm',
    'alarm_add',
    'alarm_off',
    'alarm_on',
    'album',
    'all_inbox',
    'all_inclusive',
    'all_out',
    'alt_route',
    'alternate_email',
    'amp_stories',
    'analytics',
    'anchor',
    'android',
    'announcement',
    'apartment',
    'api',
    'app_blocking',
    'app_registration',
    'app_settings_alt',
    'approval',
    'apps',
  ]
  // Añade más categorías e íconos según sea necesario
};

const Map<String, IconData> iconMap = {
  'favorite': Icons.favorite,
  'trending_up': Icons.trending_up,
  'restaurant': Icons.restaurant,
  'card_giftcard': Icons.card_giftcard,
  'directions_bus': Icons.directions_bus,
  'sports_soccer': Icons.sports_soccer,
  'work': Icons.work,
  'fitness_center': Icons.fitness_center,
  'family_restroom': Icons.family_restroom,
  'account_balance': Icons.account_balance,
  'account_balance_wallet': Icons.account_balance_wallet,
  'attach_money': Icons.attach_money,
  'credit_card': Icons.credit_card,
  'monetization_on': Icons.monetization_on,
  'money': Icons.money,
  'money_off': Icons.money_off,
  'payment': Icons.payment,
  'receipt': Icons.receipt,
  'shopping_cart': Icons.shopping_cart,
  'airplanemode_active': Icons.airplanemode_active,
  'airport_shuttle': Icons.airport_shuttle,
  'directions_bike': Icons.directions_bike,
  'fastfood': Icons.fastfood,
  'local_dining': Icons.local_dining,
  'local_drink': Icons.local_drink,
  'restaurant_menu': Icons.restaurant_menu,
  'home': Icons.home,
  'house': Icons.house,
  'house_siding': Icons.house_siding,
  'houseboat': Icons.houseboat,
  'meeting_room': Icons.meeting_room,
  'roofing': Icons.roofing,
  'health_and_safety': Icons.health_and_safety,
  'local_hospital': Icons.local_hospital,
  'local_pharmacy': Icons.local_pharmacy,
  'medical_services': Icons.medical_services,
  'sanitizer': Icons.sanitizer,
  'face': Icons.face,
  'spa': Icons.spa,
  'sports_bar': Icons.sports_bar,
  'sports_baseball': Icons.sports_baseball,
  'sports_basketball': Icons.sports_basketball,
  'movie': Icons.movie,
  'music_note': Icons.music_note,
  'theaters': Icons.theaters,
  'videogame_asset': Icons.videogame_asset,
  'account_box': Icons.account_box,
  'account_circle': Icons.account_circle,
  'account_tree': Icons.account_tree,
  'add_ic_call': Icons.add_ic_call,
  'admin_panel_settings': Icons.admin_panel_settings,
  'alarm': Icons.alarm,
  'alarm_add': Icons.alarm_add,
  'alarm_off': Icons.alarm_off,
  'alarm_on': Icons.alarm_on,
  'all_inbox': Icons.all_inbox,
  'all_out': Icons.all_out,
  'analytics': Icons.analytics,
  'anchor': Icons.anchor,
  'android': Icons.android,
  'announcement': Icons.announcement,
  'api': Icons.api,
  'app_blocking': Icons.app_blocking,
  'arrow_circle_down': Icons.arrow_circle_down,
  'arrow_circle_up': Icons.arrow_circle_up,
  'arrow_right_alt': Icons.arrow_right_alt,
  'meditation': Icons.self_improvement,
  'self_improvement': Icons.self_improvement,
  'book': Icons.book,
  'book_online': Icons.book_online,
  'class': Icons.class_,
  'library_books': Icons.library_books,
  'school': Icons.school,
  'science': Icons.science,
  'child_friendly': Icons.child_friendly,
  'stroller': Icons.stroller,
  'toys': Icons.toys,
  'agriculture': Icons.agriculture,
  'grass': Icons.grass,
  'landscape': Icons.landscape,
  'nature': Icons.nature,
  'nature_people': Icons.nature_people,
  'sailing': Icons.sailing,
  'terrain': Icons.terrain,
  'water': Icons.water,
  'add': Icons.add,
  'add_a_photo': Icons.add_a_photo,
  'add_alarm': Icons.add_alarm,
  'add_alert': Icons.add_alert,
  'add_box': Icons.add_box,
  'add_business': Icons.add_business,
  'add_call': Icons.add_call,
  'add_chart': Icons.add_chart,
  'add_circle': Icons.add_circle,
  'add_circle_outline': Icons.add_circle_outline,
  'add_comment': Icons.add_comment,
  'add_location': Icons.add_location,
  'add_location_alt': Icons.add_location_alt,
  'add_photo_alternate': Icons.add_photo_alternate,
  'add_shopping_cart': Icons.add_shopping_cart,
  'add_to_home_screen': Icons.add_to_home_screen,
  'add_to_photos': Icons.add_to_photos,
  'add_to_queue': Icons.add_to_queue,
  'addchart': Icons.addchart,
  'adjust': Icons.adjust,
  'airline_seat_flat': Icons.airline_seat_flat,
  'airline_seat_flat_angled': Icons.airline_seat_flat_angled,
  'airline_seat_individual_suite': Icons.airline_seat_individual_suite,
  'airline_seat_legroom_extra': Icons.airline_seat_legroom_extra,
  'airline_seat_legroom_normal': Icons.airline_seat_legroom_normal,
  'airline_seat_legroom_reduced': Icons.airline_seat_legroom_reduced,
  'airline_seat_recline_extra': Icons.airline_seat_recline_extra,
  'airline_seat_recline_normal': Icons.airline_seat_recline_normal,
  'airplanemode_inactive': Icons.airplanemode_inactive,
  'airplay': Icons.airplay,
  'album': Icons.album,
  'all_inclusive': Icons.all_inclusive,
  'alt_route': Icons.alt_route,
  'alternate_email': Icons.alternate_email,
  'amp_stories': Icons.amp_stories,
  'apartment': Icons.apartment,
  'app_registration': Icons.app_registration,
  'app_settings_alt': Icons.app_settings_alt,
  'approval': Icons.approval,
  'apps': Icons.apps,
  // Añade más según las categorías que hayas definido
};

IconData getIconDataByName(String iconName) {
  return iconMap[iconName] ?? Icons.help;
}

List<IconData> getIconsByCategory(String category) {
  return categorizedIcons[category]
          ?.map((iconName) => getIconDataByName(iconName))
          .toList() ??
      [];
}
